name: Build and Deploy

on:
  push:
    branches:
      - main # Cambia esto según el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install dependencies and build
      run: |
		php -S localhost:8000 -t htdocs
        

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ D117430779a }} # Cambia esto por tus credenciales de acceso
        publish_dir: ./Tarea_1 # Cambia esto según la carpeta de salida de tu compilación
